version: '3'
services:
  docker-gpio-run:
    build: .
    image: etvorellana/docker-gpio:v2
    container_name: docker-gpio-run
    #entrypoint: /bin/bash
    #command: python3 -u /home/pi/GPIO/examples/example_2-3-a-LED.py
    command: /bin/bash
    stdin_open: true
    tty: true        
    volumes:
      - ./:/home/pi/GPIO
    devices: 
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev:mem
    privileged: true
